### ISSUE TITLE
The NVIDIA driver on your system is too old

### ISSUE THREAD

**Issue by drozzy** [ai4d-iasc/trixie#9]
Tried to run pytorch training. Failed.

```
Set SLURM handle signals.
Pre-training test and predictions.
Testing:  50% 1/2 [00:00<00:00,  3.39it/s]--------------------------------------------------------------------------------
TEST RESULTS
{'test_loss': tensor(81416.4531)}
--------------------------------------------------------------------------------
Testing: 100% 2/2 [00:00<00:00,  5.64it/s]
Traceback (most recent call last):
  File "fc_model_additive.py", line 279, in <module>
    main()
  File "fc_model_additive.py", line 111, in main
    predict(module, module.test_dataloader(), num=3)
  File "fc_model_additive.py", line 264, in predict
    x_input = x_input.cuda()# if num_gpus > 1 else x_input.cpu()
  File "/home/drozdyuka/anaconda3/envs/patchy_discs_model/lib/python3.7/site-packages/torch/cuda/__init__.py", line 149, in _lazy_init
    _check_driver()
  File "/home/drozdyuka/anaconda3/envs/patchy_discs_model/lib/python3.7/site-packages/torch/cuda/__init__.py", line 63, in _check_driver
    of the CUDA driver.""".format(str(torch._C._cuda_getDriverVersion())))
AssertionError: 
The NVIDIA driver on your system is too old (found version 10010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.
```

**Comment by itamblyn** [comment]
@drozzy does this solve it?

https://github.com/ai4d-iasc/trixie/wiki/Jobs-conda-pytorch
